# -----------------------------
# Stage 1: Build Go binary
# -----------------------------
FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git ca-certificates
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o scrappy ./cmd/main.go

# -----------------------------
# Stage 2: Runtime
# -----------------------------
FROM alpine:latest

RUN apk add --no-cache ca-certificates
WORKDIR /app

# Copy Go binary
COPY --from=builder /app/scrappy .

RUN chmod +x ./scrappy

EXPOSE 8083

# Run the Go binary directly
CMD ["./scrappy"]

